default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: "postgres"

development:
  <<: *default
  database: book_app_development

test:
  <<: *default
  database: book_app_test

production:
  <<: *default
  database: book_app_production
